### ISSUE TITLE
DW: Review Dependabot alerts

### ISSUE THREAD

**Issue by Curt-Whitmire-NOAA** [nwfsc-fram/warehouse#79]
@Mak-NOAA, can you please review the following Dependabot alerts. Is the current requirements.txt file accurate, or should we consider updating the various dependencies?

**Comment by Mak-NOAA** [comment]
I have merged the changes into requirements.txt 

I looked at the change log for each upgrade and it looks ok to me however testing this in reality requires recompiling the backend which is another journey.  If we ever need to rebuild the backend (in an emergency), then we'll have to see if these upgrades cause any errors.
